#! /bin/bash

#
#	git backup for TOPAZ
#

cp  $HOME/.config/bspwm/bspwmrc $HOME/dl/git/clones/internal/bspwm/ &&
cp  $HOME/.config/sxhkd/sxhkdrc $HOME/dl/git/clones/internal/bspwm/ &&
cp -r $HOME/.scripts $HOME/dl/git/clones/internal/bspwm/ &&
echo "copied files"
sleep 1
echo "what would you like to commit?"
read commit
echo "$commit"
