#! /bin/sh

#
#	BSPWM config for TOPAZ
#

#
# 	default bspwm stuff
#

bspc config focus_follows_pointer true
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor eDP-1 -d 1 2 3 4 5
bspc rule -r "*"
. "${HOME}/.cache/wal/colors.sh"
# 	cursor fix
xsetroot -cursor_name left_ptr &
for monitor in $desktops; do
    [ "$IsInitialRun" = true ] && \
        bspc monitor "$monitor" -n $i -d $i/{00,01,10,11} || \
        bspc monitor "$monitor" -d $i/{00,01,10,11}
    let i++
done

bspc config border_width         3
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 22	

# 	set the border colors.
bspc config normal_border_color "$color3"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color1"

#
#	startup stuff
#

picom --shadow --round-borders 3 --corner-radius 3 --vsync &
redshift &
polybar --config=.config/polybar/config.ini example &
wal -R &
dunst &
reload_dunst.sh & 
#feh --bg-tile /home/joel/media/images/wallpapers/oriental-tiles.png & 
