--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/joel/.config/wpg/wallpapers/pink-feather.png"

-- Special
background="#0f0f0f"
foreground="#fffdf1"
cursor="#fffdf1"

-- Colors
color0="#0f0f0f"
color1="#f05365"
color2="#4a7c59"
color3="#edd9a3"
color4="#1d70a2"
color5="#fcf6bd"
color6="#52d1dc"
color7="#f9ebe0"
color8="#282828"
color9="#ff5673"
color10="#53ae6e"
color11="#ffffb6"
color12="#1994df"
color13="#ffffc1"
color14="#56ffff"
color15="#fffdf1"
